[alias]
# binaries
build-esteem = "build --package esteem --target i686-unknown-linux-gnu --release --"
build-error-reporter = "build --package esteem-error-reporter --release --"
build-reaper = "build --package esteem-reaper --release --"
build-zenity = "build --package esteem-zenity --release --"

# libs
build-libpipewire = "build --package pipewire --target i686-unknown-linux-gnu --release --"
build-libnm = "build --package nm --target i686-unknown-linux-gnu --release --"
build-libvideo = "build --package video --target i686-unknown-linux-gnu --release --"
