[alias]
# binaries
build-esteem = "build --package esteem --target i686-unknown-linux-gnu --release --"
build-error-reporter = "build --package esteem-error-reporter --target i686-unknown-linux-gnu --release --"
build-reaper = "build --package esteem-reaper --target i686-unknown-linux-gnu --release --"
build-zenity = "build --package esteem-zenity --target i686-unknown-linux-gnu --release --"

# libs
build-libpipewire = "build --package pipewire --target i686-unknown-linux-gnu --release --"
build-libnm = "build --package nm --target i686-unknown-linux-gnu --release --"
