[package]
edition = "2021"
name = "vstdlib_s"
version = "0.0.0"

[dependencies.esteem-util]
path = "../util"

[dependencies.frosting]
git = "https://github.com/elysian6969/frosting"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
